/**
 * RFC 7807 Problem Details for HTTP APIs
 *
 * A standard error response format that provides machine-readable details
 * about errors in HTTP APIs.
 *
 * @see https://datatracker.ietf.org/doc/html/rfc7807
 */

/**
 * Problem Details interface (RFC 7807 compliant)
 */
export interface ProblemDetails {
  /**
   * A URI reference (RFC3986) that identifies the problem type
   * When dereferenced, it should provide human-readable documentation
   * for the problem type (e.g., using HTML).
   */
  type: string;

  /**
   * A short, human-readable summary of the problem type
   * It SHOULD NOT change from occurrence to occurrence of the problem
   */
  title: string;

  /**
   * The HTTP status code (RFC7231, Section 6) generated by the origin server
   */
  status: number;

  /**
   * A human-readable explanation specific to this occurrence of the problem
   */
  detail?: string;

  /**
   * A URI reference that identifies the specific occurrence of the problem
   * It may or may not yield further information if dereferenced
   */
  instance?: string;

  /**
   * Extension members - additional problem-specific fields
   */
  [key: string]: unknown;
}

/**
 * Factory function to create RFC 7807 Problem Details
 */
export function createProblemDetails(options: {
  type: string;
  title: string;
  status: number;
  detail?: string;
  instance?: string;
  extensions?: Record<string, unknown>;
}): ProblemDetails {
  const problemDetails: ProblemDetails = {
    type: options.type,
    title: options.title,
    status: options.status,
  };

  if (options.detail) {
    problemDetails.detail = options.detail;
  }

  if (options.instance) {
    problemDetails.instance = options.instance;
  }

  // Add extension members
  if (options.extensions) {
    Object.assign(problemDetails, options.extensions);
  }

  return problemDetails;
}

/**
 * Common problem type URIs
 */
export const PROBLEM_TYPES = {
  VALIDATION_ERROR: 'https://api.architrack.com/errors/validation-error',
  UNAUTHORIZED: 'https://api.architrack.com/errors/unauthorized',
  FORBIDDEN: 'https://api.architrack.com/errors/forbidden',
  NOT_FOUND: 'https://api.architrack.com/errors/not-found',
  CONFLICT: 'https://api.architrack.com/errors/conflict',
  INTERNAL_SERVER_ERROR: 'https://api.architrack.com/errors/internal-server-error',
  BAD_REQUEST: 'https://api.architrack.com/errors/bad-request',
  WEAK_PASSWORD: 'https://api.architrack.com/errors/weak-password',
  ACCOUNT_LOCKED: 'https://api.architrack.com/errors/account-locked',
  INVALID_CREDENTIALS: 'https://api.architrack.com/errors/invalid-credentials',
  TOKEN_EXPIRED: 'https://api.architrack.com/errors/token-expired',
  PROJECT_NAME_DUPLICATE: 'https://api.architrack.com/errors/project-name-duplicate',
  BUSINESS_RULE_VIOLATION: 'https://api.architrack.com/errors/business-rule-violation',
} as const;
