/**
 * @fileoverview 帳票構成の基準出力（Task 57.5 の書き換え前＝自己再帰版が生成した実測値）
 *
 * `reportLayoutFixtures.LAYOUT_FIXTURES` の各フィクスチャに対する `buildFiles` の戻り値を
 * `reportLayoutFixtures.serializeFiles` で直列化したもの。明細書ページの組み立てを
 * 自己再帰から明示スタックの反復へ書き換えても、**ページの中身と並び順が一切変わらない**
 * ことを突き合わせるための基準であり、手で編集してはならない（実装の変更に合わせて
 * 書き換えると、この検証そのものが無意味になる）。
 *
 * Requirements (estimate-creation): 2.5, 50.5, 50.6, 50.9, 50.10
 */

export const REPORT_LAYOUT_GOLDEN: readonly string[] = [
  '=== 空のツリー・見積のみ ===',
  'FILE ESTIMATE label=見積 cover=true pages=2',
  '  PAGE 1 kind=cover lineType=ESTIMATE title=御見積書 parent=null rows=0',
  '    TOTAL (none)',
  '  PAGE 2 kind=summary lineType=ESTIMATE title=内訳書（見積） parent=null rows=0',
  '    TOTAL total | 【合計】 |  |  |  |  |  |  | 0',
  '=== 深さ4階層・兄弟複数・見積 ===',
  'FILE ESTIMATE label=見積 cover=true pages=7',
  '  PAGE 1 kind=cover lineType=ESTIMATE title=御見積書 parent=null rows=0',
  '    TOTAL (none)',
  '  PAGE 2 kind=summary lineType=ESTIMATE title=内訳書（見積） parent=null rows=3',
  '    ROW 0 item | Ａ.建築工事 |  | 式 | 1      |  | 25,000 |  | 0',
  '    ROW 1 item | Ｂ.電気工事 |  | 〃 | 1      |  | 16,000 |  | 0',
  '    ROW 2 item | Ｃ.諸経費 |  | 〃 | 1      |  | 3,000 |  | 0',
  '    TOTAL total | 【合計】 |  |  |  |  | 44,000 |  | 0',
  '  PAGE 3 kind=detail lineType=ESTIMATE title=明細書（見積） parent=Ａ.建築工事 rows=17',
  '    ROW 0 item | Ａ.建築工事 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 建築0 |  | 式 | 1      |  | 1,000 |  | 1',
  '    ROW 2 item | 建築1 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 3 item | 建築2 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 4 item | 建築3 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 5 item | 内装工事 |  | 〃 | 1      |  | 6,000 |  | 1',
  '    ROW 6 item | 建築5 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 7 item | 建築6 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 8 item | 建築7 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 9 item | 建築8 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 10 item | 建築9 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 11 item | 建築10 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 12 item | 建築11 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 13 item | 建築12 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 14 item | 建築13 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 15 item | 建築14 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 16 item | 建築15 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    TOTAL (none)',
  '  PAGE 4 kind=detail lineType=ESTIMATE title=明細書（見積） parent=Ａ.建築工事 rows=4',
  '    ROW 0 item | 建築16 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 1 item | 建築17 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 2 item | 建築18 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 3 item | 建築19 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 25,000 |  | 0',
  '  PAGE 5 kind=detail lineType=ESTIMATE title=明細書（見積） parent=内装工事 rows=13',
  '    ROW 0 item | 内装工事 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 内装0 |  | ㎡ | 1      |  | 500 |  | 1',
  '    ROW 2 item | 内装1 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 3 item | 内装2 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 4 item | 内装3 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 5 item | 内装4 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 6 item | 内装5 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 7 item | 内装6 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 8 item | 内装7 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 9 item | 内装8 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 10 item | 内装9 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 11 item | 内装10 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 12 item | 内装11 |  | 〃 | 1      |  | 500 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 6,000 |  | 0',
  '  PAGE 6 kind=detail lineType=ESTIMATE title=明細書（見積） parent=内装2 rows=4',
  '    ROW 0 item | 内装2 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 塗装0 |  | ㎡ | 1      |  | 100 |  | 1',
  '    ROW 2 item | 塗装1 |  | 〃 | 1      |  | 100 |  | 1',
  '    ROW 3 item | 塗装2 |  | 〃 | 1      |  | 100 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 300 |  | 0',
  '  PAGE 7 kind=detail lineType=ESTIMATE title=明細書（見積） parent=Ｂ.電気工事 rows=9',
  '    ROW 0 item | Ｂ.電気工事 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 電気0 |  | 式 | 1      |  | 2,000 |  | 1',
  '    ROW 2 item | 電気1 |  | 〃 | 1      |  | 2,000 |  | 1',
  '    ROW 3 item | 電気2 |  | 〃 | 1      |  | 2,000 |  | 1',
  '    ROW 4 item | 電気3 |  | 〃 | 1      |  | 2,000 |  | 1',
  '    ROW 5 item | 電気4 |  | 〃 | 1      |  | 2,000 |  | 1',
  '    ROW 6 item | 電気5 |  | 〃 | 1      |  | 2,000 |  | 1',
  '    ROW 7 item | 電気6 |  | 〃 | 1      |  | 2,000 |  | 1',
  '    ROW 8 item | 電気7 |  | 〃 | 1      |  | 2,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 16,000 |  | 0',
  '=== 深さ4階層・兄弟複数・3行タイプ ===',
  'FILE ESTIMATE label=見積 cover=true pages=7',
  '  PAGE 1 kind=cover lineType=ESTIMATE title=御見積書 parent=null rows=0',
  '    TOTAL (none)',
  '  PAGE 2 kind=summary lineType=ESTIMATE title=内訳書（見積） parent=null rows=3',
  '    ROW 0 item | Ａ.建築工事 |  | 式 | 1      |  | 25,000 |  | 0',
  '    ROW 1 item | Ｂ.電気工事 |  | 〃 | 1      |  | 16,000 |  | 0',
  '    ROW 2 item | Ｃ.諸経費 |  | 〃 | 1      |  | 3,000 |  | 0',
  '    TOTAL total | 【合計】 |  |  |  |  | 44,000 |  | 0',
  '  PAGE 3 kind=detail lineType=ESTIMATE title=明細書（見積） parent=Ａ.建築工事 rows=17',
  '    ROW 0 item | Ａ.建築工事 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 建築0 |  | 式 | 1      |  | 1,000 |  | 1',
  '    ROW 2 item | 建築1 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 3 item | 建築2 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 4 item | 建築3 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 5 item | 内装工事 |  | 〃 | 1      |  | 6,000 |  | 1',
  '    ROW 6 item | 建築5 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 7 item | 建築6 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 8 item | 建築7 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 9 item | 建築8 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 10 item | 建築9 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 11 item | 建築10 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 12 item | 建築11 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 13 item | 建築12 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 14 item | 建築13 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 15 item | 建築14 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 16 item | 建築15 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    TOTAL (none)',
  '  PAGE 4 kind=detail lineType=ESTIMATE title=明細書（見積） parent=Ａ.建築工事 rows=4',
  '    ROW 0 item | 建築16 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 1 item | 建築17 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 2 item | 建築18 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 3 item | 建築19 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 25,000 |  | 0',
  '  PAGE 5 kind=detail lineType=ESTIMATE title=明細書（見積） parent=内装工事 rows=13',
  '    ROW 0 item | 内装工事 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 内装0 |  | ㎡ | 1      |  | 500 |  | 1',
  '    ROW 2 item | 内装1 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 3 item | 内装2 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 4 item | 内装3 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 5 item | 内装4 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 6 item | 内装5 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 7 item | 内装6 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 8 item | 内装7 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 9 item | 内装8 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 10 item | 内装9 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 11 item | 内装10 |  | 〃 | 1      |  | 500 |  | 1',
  '    ROW 12 item | 内装11 |  | 〃 | 1      |  | 500 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 6,000 |  | 0',
  '  PAGE 6 kind=detail lineType=ESTIMATE title=明細書（見積） parent=内装2 rows=4',
  '    ROW 0 item | 内装2 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 塗装0 |  | ㎡ | 1      |  | 100 |  | 1',
  '    ROW 2 item | 塗装1 |  | 〃 | 1      |  | 100 |  | 1',
  '    ROW 3 item | 塗装2 |  | 〃 | 1      |  | 100 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 300 |  | 0',
  '  PAGE 7 kind=detail lineType=ESTIMATE title=明細書（見積） parent=Ｂ.電気工事 rows=9',
  '    ROW 0 item | Ｂ.電気工事 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 電気0 |  | 式 | 1      |  | 2,000 |  | 1',
  '    ROW 2 item | 電気1 |  | 〃 | 1      |  | 2,000 |  | 1',
  '    ROW 3 item | 電気2 |  | 〃 | 1      |  | 2,000 |  | 1',
  '    ROW 4 item | 電気3 |  | 〃 | 1      |  | 2,000 |  | 1',
  '    ROW 5 item | 電気4 |  | 〃 | 1      |  | 2,000 |  | 1',
  '    ROW 6 item | 電気5 |  | 〃 | 1      |  | 2,000 |  | 1',
  '    ROW 7 item | 電気6 |  | 〃 | 1      |  | 2,000 |  | 1',
  '    ROW 8 item | 電気7 |  | 〃 | 1      |  | 2,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 16,000 |  | 0',
  'FILE EXECUTION label=実行 cover=false pages=1',
  '  PAGE 1 kind=summary lineType=EXECUTION title=内訳書（実行） parent=null rows=0',
  '    TOTAL total | 【合計】 |  |  |  |  |  |  | 0',
  'FILE VENDOR label=業者 cover=false pages=1',
  '  PAGE 1 kind=summary lineType=VENDOR title=内訳書（業者） parent=null rows=0',
  '    TOTAL total | 【合計】 |  |  |  |  |  |  | 0',
  '=== 注記行と値引き行・見積 ===',
  'FILE ESTIMATE label=見積 cover=true pages=5',
  '  PAGE 1 kind=cover lineType=ESTIMATE title=御見積書 parent=null rows=0',
  '    TOTAL (none)',
  '  PAGE 2 kind=summary lineType=ESTIMATE title=内訳書（見積） parent=null rows=1',
  '    ROW 0 item | Ａ.建築工事 |  | 式 | 1      |  | 14,500 |  | 0',
  '    TOTAL total | 【合計】 |  |  |  |  | 14,500 |  | 0',
  '  PAGE 3 kind=detail lineType=ESTIMATE title=明細書（見積） parent=Ａ.建築工事 rows=17',
  '    ROW 0 item | Ａ.建築工事 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 子00 |  | ㎡ | 1      |  | 1,000 |  | 1',
  '    ROW 2 item | 子01 |  | 式 | 1      |  | 1,000 |  | 1',
  '    ROW 3 note | ※別途消費税 |  |  |  |  |  |  | 1',
  '    ROW 4 item | 子02 |  | 式 | 1      |  | 1,000 |  | 1',
  '    ROW 5 item | 子03 |  | ㎡ | 1      |  | 1,000 |  | 1',
  '    ROW 6 item | 子04 |  | 式 | 1      |  | 1,000 |  | 1',
  '    ROW 7 item | 子05 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 8 item | 子06 |  | ㎡ | 1      |  | 1,000 |  | 1',
  '    ROW 9 item | 子07 |  | 式 | 1      |  | 1,000 |  | 1',
  '    ROW 10 discount | 【値引】 |  | 〃 | 1      |  | -500 |  | 1',
  '    ROW 11 item | 子08 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 12 item | 子09 |  | ㎡ | 1      |  | 1,000 |  | 1',
  '    ROW 13 item | 子10 |  | 式 | 1      |  | 1,000 |  | 1',
  '    ROW 14 item | 子11 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 15 item | 子12 |  | ㎡ | 1      |  | 1,000 |  | 1',
  '    ROW 16 item | 子13 |  | 式 | 1      |  | 1,000 |  | 1',
  '    TOTAL (none)',
  '  PAGE 4 kind=detail lineType=ESTIMATE title=明細書（見積） parent=Ａ.建築工事 rows=2',
  '    ROW 0 item | 子14 |  | 〃 | 1      |  | 1,000 |  | 1',
  '    ROW 1 item | 入れ子 |  | 〃 | 1      |  | 2,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 16,500 |  | 0',
  '  PAGE 5 kind=detail lineType=ESTIMATE title=明細書（見積） parent=入れ子 rows=2',
  '    ROW 0 item | 入れ子 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 入れ子の子 |  | ㎡ | 1      |  | 2,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 2,000 |  | 0',
  '=== 注記行と値引き行・実行 ===',
  'FILE EXECUTION label=実行 cover=false pages=1',
  '  PAGE 1 kind=summary lineType=EXECUTION title=内訳書（実行） parent=null rows=0',
  '    TOTAL total | 【合計】 |  |  |  |  |  |  | 0',
  '=== 値を持たない親の部分木脱落・見積と実行 ===',
  'FILE ESTIMATE label=見積 cover=true pages=5',
  '  PAGE 1 kind=cover lineType=ESTIMATE title=御見積書 parent=null rows=0',
  '    TOTAL (none)',
  '  PAGE 2 kind=summary lineType=ESTIMATE title=内訳書（見積） parent=null rows=1',
  '    ROW 0 item | Ａ.両方持つ工事 |  | 式 | 1      |  | 9,000 |  | 0',
  '    TOTAL total | 【合計】 |  |  |  |  | 9,000 |  | 0',
  '  PAGE 3 kind=detail lineType=ESTIMATE title=明細書（見積） parent=Ａ.両方持つ工事 rows=3',
  '    ROW 0 item | Ａ.両方持つ工事 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 見積のみの親 |  | 式 | 1      |  | 4,000 |  | 1',
  '    ROW 2 item | 両方持つ親 |  | 〃 | 1      |  | 5,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 9,000 |  | 0',
  '  PAGE 4 kind=detail lineType=ESTIMATE title=明細書（見積） parent=見積のみの親 rows=2',
  '    ROW 0 item | 見積のみの親 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 実行も持つ孫 |  | 式 | 1      |  | 4,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 4,000 |  | 0',
  '  PAGE 5 kind=detail lineType=ESTIMATE title=明細書（見積） parent=両方持つ親 rows=2',
  '    ROW 0 item | 両方持つ親 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 両方持つ子 |  | 式 | 1      |  | 5,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 5,000 |  | 0',
  'FILE EXECUTION label=実行 cover=false pages=3',
  '  PAGE 1 kind=summary lineType=EXECUTION title=内訳書（実行） parent=null rows=1',
  '    ROW 0 item | Ａ.両方持つ工事 |  | 式 | 1      |  | 9,000 |  | 0',
  '    TOTAL total | 【合計】 |  |  |  |  | 9,000 |  | 0',
  '  PAGE 2 kind=detail lineType=EXECUTION title=明細書（実行） parent=Ａ.両方持つ工事 rows=2',
  '    ROW 0 item | Ａ.両方持つ工事 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 両方持つ親 |  | 式 | 1      |  | 5,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 5,000 |  | 0',
  '  PAGE 3 kind=detail lineType=EXECUTION title=明細書（実行） parent=両方持つ親 rows=2',
  '    ROW 0 item | 両方持つ親 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 両方持つ子 |  | 式 | 1      |  | 5,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 5,000 |  | 0',
  '=== 第1階層30件・見積 ===',
  'FILE ESTIMATE label=見積 cover=true pages=8',
  '  PAGE 1 kind=cover lineType=ESTIMATE title=御見積書 parent=null rows=0',
  '    TOTAL (none)',
  '  PAGE 2 kind=summary lineType=ESTIMATE title=内訳書（見積） parent=null rows=17',
  '    ROW 0 item | Ａ.工事00 |  | 式 | 1      |  | 1,000 |  | 0',
  '    ROW 1 item | Ｂ.工事01 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 2 item | Ｃ.工事02 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 3 item | Ｄ.工事03 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 4 item | Ｅ.工事04 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 5 item | Ｆ.工事05 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 6 item | Ｇ.工事06 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 7 item | Ｈ.工事07 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 8 item | Ｉ.工事08 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 9 item | Ｊ.工事09 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 10 item | Ｋ.工事10 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 11 item | Ｌ.工事11 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 12 item | Ｍ.工事12 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 13 item | Ｎ.工事13 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 14 item | Ｏ.工事14 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 15 item | Ｐ.工事15 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 16 item | Ｑ.工事16 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    TOTAL (none)',
  '  PAGE 3 kind=summary lineType=ESTIMATE title=内訳書（見積） parent=null rows=13',
  '    ROW 0 item | Ｒ.工事17 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 1 item | Ｓ.工事18 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 2 item | Ｔ.工事19 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 3 item | Ｕ.工事20 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 4 item | Ｖ.工事21 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 5 item | Ｗ.工事22 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 6 item | Ｘ.工事23 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 7 item | Ｙ.工事24 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 8 item | Ｚ.工事25 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 9 item | ＡＡ.工事26 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 10 item | ＡＢ.工事27 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 11 item | ＡＣ.工事28 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    ROW 12 item | ＡＤ.工事29 |  | 〃 | 1      |  | 1,000 |  | 0',
  '    TOTAL total | 【合計】 |  |  |  |  | 30,000 |  | 0',
  '  PAGE 4 kind=detail lineType=ESTIMATE title=明細書（見積） parent=Ａ.工事00 rows=2',
  '    ROW 0 item | Ａ.工事00 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 子0 |  | ㎡ | 1      |  | 1,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 1,000 |  | 0',
  '  PAGE 5 kind=detail lineType=ESTIMATE title=明細書（見積） parent=Ｈ.工事07 rows=2',
  '    ROW 0 item | Ｈ.工事07 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 子7 |  | ㎡ | 1      |  | 1,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 1,000 |  | 0',
  '  PAGE 6 kind=detail lineType=ESTIMATE title=明細書（見積） parent=Ｏ.工事14 rows=2',
  '    ROW 0 item | Ｏ.工事14 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 子14 |  | ㎡ | 1      |  | 1,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 1,000 |  | 0',
  '  PAGE 7 kind=detail lineType=ESTIMATE title=明細書（見積） parent=Ｖ.工事21 rows=2',
  '    ROW 0 item | Ｖ.工事21 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 子21 |  | ㎡ | 1      |  | 1,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 1,000 |  | 0',
  '  PAGE 8 kind=detail lineType=ESTIMATE title=明細書（見積） parent=ＡＣ.工事28 rows=2',
  '    ROW 0 item | ＡＣ.工事28 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 子28 |  | ㎡ | 1      |  | 1,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 1,000 |  | 0',
  '=== 一本鎖の深さ8・見積 ===',
  'FILE ESTIMATE label=見積 cover=true pages=9',
  '  PAGE 1 kind=cover lineType=ESTIMATE title=御見積書 parent=null rows=0',
  '    TOTAL (none)',
  '  PAGE 2 kind=summary lineType=ESTIMATE title=内訳書（見積） parent=null rows=1',
  '    ROW 0 item | Ａ.階層0 |  | 式 | 1      |  | 1,000 |  | 0',
  '    TOTAL total | 【合計】 |  |  |  |  | 1,000 |  | 0',
  '  PAGE 3 kind=detail lineType=ESTIMATE title=明細書（見積） parent=Ａ.階層0 rows=2',
  '    ROW 0 item | Ａ.階層0 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 階層1 |  | 式 | 1      |  | 1,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 1,000 |  | 0',
  '  PAGE 4 kind=detail lineType=ESTIMATE title=明細書（見積） parent=階層1 rows=2',
  '    ROW 0 item | 階層1 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 階層2 |  | 式 | 1      |  | 1,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 1,000 |  | 0',
  '  PAGE 5 kind=detail lineType=ESTIMATE title=明細書（見積） parent=階層2 rows=2',
  '    ROW 0 item | 階層2 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 階層3 |  | 式 | 1      |  | 1,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 1,000 |  | 0',
  '  PAGE 6 kind=detail lineType=ESTIMATE title=明細書（見積） parent=階層3 rows=2',
  '    ROW 0 item | 階層3 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 階層4 |  | 式 | 1      |  | 1,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 1,000 |  | 0',
  '  PAGE 7 kind=detail lineType=ESTIMATE title=明細書（見積） parent=階層4 rows=2',
  '    ROW 0 item | 階層4 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 階層5 |  | 式 | 1      |  | 1,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 1,000 |  | 0',
  '  PAGE 8 kind=detail lineType=ESTIMATE title=明細書（見積） parent=階層5 rows=2',
  '    ROW 0 item | 階層5 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 階層6 |  | 式 | 1      |  | 1,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 1,000 |  | 0',
  '  PAGE 9 kind=detail lineType=ESTIMATE title=明細書（見積） parent=階層6 rows=2',
  '    ROW 0 item | 階層6 |  |  |  |  |  |  | 0',
  '    ROW 1 item | 階層7 |  | 式 | 1      |  | 1,000 |  | 1',
  '    TOTAL total | 【合計】 |  |  |  |  | 1,000 |  | 0',
];
